version: '3'

services:
  easynode:
    image: chaoszhu/easynode
    restart: always
    ports:
      - 8082:8082
    volumes:
      - /root/easynode/db:/easynode/app/db
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=0
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 8 * * *" --label-enable
    restart: always
    environment:
      - TZ=Asia/Shanghai
